### ISSUE TITLE
Time in weather data different from time in image data

### ISSUE THREAD

**Issue by bartastro** [tcpalmer/nina.plugin.sessionmetadata#22]
Hi,

First of all: thanks for this great plugin, I started to use this recently.

When analyzing the first results it seems that the exposure starttime in the image meta data file is using the **local time** (in my case timezone is GMT+1 and as daylightsaving is on it is now GMT+2).  However when looking at the weather meta data the time for the same exposurenumber is in **GMT** (no not adjusted to the local time zone).  As such, when trying to combine this data one has to add the timezone offset and the daylightsaving to achieve a matching exposure starttime value.

Is that expected?

Regards,  Bart

**Comment by tcpalmer** [comment]
Fixed in the latest release

**Comment by bartastro** [comment]
Hi,

Thanks!  Great plugin.

Best regards, Bart

Op wo 8 mei 2024 17:57 schreef tcpalmer ***@***.***>:
