### ISSUE TITLE
Add Seconds to date format

### ISSUE THREAD

**Issue by JuergenTerpe** [tcpalmer/nina.plugin.sessionmetadata#23]
Hi Tom,

Would you please consider adding the seconds to the date format for ImageMetadata/WeatherData in csv/json format? 

I'm writing an app which uses these files together with the PHD2 guide log and the NINA log to analyze and evaluate the entire NINA session, which works fine for FITS files having all the exact times within the header. But now the DSLR users want to use this tool too and I'm limited to these files. However, using just a one minute accuracy is just useless when trying to match the guiding during an exposure - every calculation will be useless and many graphs would be misleading. 

I have a second wish: do you have also access to the plate solved RA/DEC coordinates for the current image and can you add this current coordinates for each image too? Currently, I'm showing a drift graph for the fits images with rotation and exact matched framing, which gives an excellent overview how the dithering works. But I need to disable this for DSLRs, because I only have the Target coordinates from the AcquisitionDetails.csv. 

You can find my free tool here (with a little bit older screenshots) : https://www.ideviceapps.de/n.i.n.a.-session-analysis.html  
(It's only for macOS until now)

Best regards and Thanks in advance from all DSLR users,

Jürgen  Terpe

**Comment by tcpalmer** [comment]
I can add seconds, but I think I'll do it by adding new UTC date/time elements rather than changing the current time output.  I've recently make changes to the current time (which is local) so that should remain as is.  But there is value in having UTC time to the second as well.  Are you OK translating from UTC to local in your tool?

Although you don't have access to the actual plate solve coordinates, you do have the current position of the mount at the time each image was saved - this would be the same as the RA and DEC FITS elements.  This could be added to the Image metadata records - does that work for you?

**Comment by JuergenTerpe** [comment]
I really would appreciate an UTC time! Currently, it is a nightmare, because PHD2 and NINA are logging - of course - in the local machine time, and all the image meta data/weather data also have local time. In order to match all these things together I'm using the Julian date based on UTC, but transforming the things to UTC requires a timezone setting to be set correctly before reading the data. I had hard times to figure out how this could work correctly together. 

The mount coordinates would be fine, as long as they are given including the arc seconds.  The format does not matter for me, can be human readable or just degrees with enough digits.  

 Thank you!!!

**Comment by tcpalmer** [comment]
Added ExposureStartUTC, MountRA, and MountDec elements.  See attached samples.  This was done with simulated equipment so some data elements are missing.  Note that the UTC format uses standard ISO 8601 which includes milliseconds.  Look OK?
[ImageMetaData.csv](https://github.com/tcpalmer/nina.plugin.sessionmetadata/files/15447113/ImageMetaData.csv)
[ImageMetaData.json](https://github.com/tcpalmer/nina.plugin.sessionmetadata/files/15447114/ImageMetaData.json)

**Comment by JuergenTerpe** [comment]
Really exciting! Looks good! 

Thanks for your fast response!

**Comment by tcpalmer** [comment]
Released in version 2.5.1.0 - enjoy
